# settings/__init__.py
"""
Django settings for server project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

from .base import *
from .apps import *

# {% if cookiecutter.database == "sqlite" %}
from .database_dev import *
# {% elif cookiecutter.database == "postgresql" %}
# from .database_prod import *
# {% endif %}

from .middleware import *

from .templates import *
from .static import *
from .auth import *
from .i18n import *
from .security import *
# from .drf import *
# from .email import *
# from .cache import *
# from .logging import *
from .debug_toolbar import *
