# settings/security.py
from .base import env

FIELD_ENCRYPTION_KEY = env.list("FIELD_ENCRYPTION_KEY", "")

RECAPTCHA_PUBLIC_KEY = env("RECAPTCHA_PUBLIC_KEY")
RECAPTCHA_PRIVATE_KEY = env("RECAPTCHA_PRIVATE_KEY")
RECAPTCHA_REQUIRED_SCORE = 0.85
