# Generated by Django 5.2 on 2025-04-09 11:57

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="first_name",
            field=encrypted_model_fields.fields.EncryptedCharField(
                blank=True, verbose_name="first name"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="last_name",
            field=encrypted_model_fields.fields.EncryptedCharField(
                blank=True, verbose_name="last name"
            ),
        ),
    ]
