# Generated by Django 5.2 on 2025-04-09 12:02

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_customuser_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerprofile",
            name="company_name",
            field=encrypted_model_fields.fields.EncryptedCharField(
                blank=True, verbose_name="Company name"
            ),
        ),
    ]
