# Generated by Django 5.2 on 2025-04-09 12:56

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_customerprofile_company_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplierprofile",
            name="company_name",
            field=encrypted_model_fields.fields.EncryptedCharField(
                blank=True, verbose_name="Company name"
            ),
        ),
    ]
