# Generated by Django 5.2 on 2025-04-09 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_supplierprofile_company_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customerprofile",
            old_name="modified",
            new_name="updated",
        ),
        migrations.RenameField(
            model_name="supplierprofile",
            old_name="modified",
            new_name="updated",
        ),
    ]
