# Generated by Django 5.2 on 2025-04-10 09:55

import django.db.models.deletion
import django_countries.fields
import encrypted_model_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0006_alter_customuser_options_alter_customuser_email_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.IntegerField(
                        choices=[(1, "private"), (2, "professional"), (3, "other")],
                        default=1,
                    ),
                ),
                (
                    "address_line1",
                    encrypted_model_fields.fields.EncryptedCharField(
                        verbose_name="Address line 1"
                    ),
                ),
                (
                    "address_line2",
                    encrypted_model_fields.fields.EncryptedCharField(
                        blank=True, verbose_name="Address line 2"
                    ),
                ),
                (
                    "postal_code",
                    encrypted_model_fields.fields.EncryptedCharField(
                        verbose_name="Postal code"
                    ),
                ),
                (
                    "city",
                    encrypted_model_fields.fields.EncryptedCharField(
                        verbose_name="City"
                    ),
                ),
                (
                    "state",
                    encrypted_model_fields.fields.EncryptedCharField(
                        blank=True, null=True, verbose_name="State"
                    ),
                ),
                ("country", django_countries.fields.CountryField(max_length=2)),
                (
                    "latitude",
                    encrypted_model_fields.fields.EncryptedCharField(
                        blank=True, null=True, verbose_name="Latitude"
                    ),
                ),
                (
                    "longitude",
                    encrypted_model_fields.fields.EncryptedCharField(
                        blank=True, null=True, verbose_name="Longitude"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to="accounts.customerprofile",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CustomerEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.IntegerField(
                        choices=[(1, "private"), (2, "professional"), (3, "other")],
                        default=1,
                    ),
                ),
                (
                    "email",
                    encrypted_model_fields.fields.EncryptedEmailField(blank=True),
                ),
                ("default", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emails",
                        to="accounts.customerprofile",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CustomerPhone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "device_type",
                    models.IntegerField(
                        choices=[(1, "cell phone"), (2, "phone"), (3, "fax machine")],
                        default=2,
                    ),
                ),
                (
                    "title",
                    models.IntegerField(
                        choices=[(1, "private"), (2, "professional"), (3, "other")],
                        default=1,
                    ),
                ),
                (
                    "number",
                    encrypted_model_fields.fields.EncryptedCharField(blank=True),
                ),
                ("default_sms_phone_number", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phones",
                        to="accounts.customerprofile",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CustomerWebsite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.IntegerField(
                        choices=[(1, "private"), (2, "professional"), (3, "other")],
                        default=1,
                    ),
                ),
                ("website", models.URLField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="websites",
                        to="accounts.customerprofile",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SupplierAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.IntegerField(
                        choices=[(1, "private"), (2, "professional"), (3, "other")],
                        default=1,
                    ),
                ),
                (
                    "address_line1",
                    encrypted_model_fields.fields.EncryptedCharField(
                        verbose_name="Address line 1"
                    ),
                ),
                (
                    "address_line2",
                    encrypted_model_fields.fields.EncryptedCharField(
                        blank=True, verbose_name="Address line 2"
                    ),
                ),
                (
                    "postal_code",
                    encrypted_model_fields.fields.EncryptedCharField(
                        verbose_name="Postal code"
                    ),
                ),
                (
                    "city",
                    encrypted_model_fields.fields.EncryptedCharField(
                        verbose_name="City"
                    ),
                ),
                (
                    "state",
                    encrypted_model_fields.fields.EncryptedCharField(
                        blank=True, null=True, verbose_name="State"
                    ),
                ),
                ("country", django_countries.fields.CountryField(max_length=2)),
                (
                    "latitude",
                    encrypted_model_fields.fields.EncryptedCharField(
                        blank=True, null=True, verbose_name="Latitude"
                    ),
                ),
                (
                    "longitude",
                    encrypted_model_fields.fields.EncryptedCharField(
                        blank=True, null=True, verbose_name="Longitude"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to="accounts.supplierprofile",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SupplierEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.IntegerField(
                        choices=[(1, "private"), (2, "professional"), (3, "other")],
                        default=1,
                    ),
                ),
                (
                    "email",
                    encrypted_model_fields.fields.EncryptedEmailField(blank=True),
                ),
                ("default", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emails",
                        to="accounts.supplierprofile",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SupplierPhone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "device_type",
                    models.IntegerField(
                        choices=[(1, "cell phone"), (2, "phone"), (3, "fax machine")],
                        default=2,
                    ),
                ),
                (
                    "title",
                    models.IntegerField(
                        choices=[(1, "private"), (2, "professional"), (3, "other")],
                        default=1,
                    ),
                ),
                (
                    "number",
                    encrypted_model_fields.fields.EncryptedCharField(blank=True),
                ),
                ("default_sms_phone_number", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phones",
                        to="accounts.supplierprofile",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SupplierWebsite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.IntegerField(
                        choices=[(1, "private"), (2, "professional"), (3, "other")],
                        default=1,
                    ),
                ),
                ("website", models.URLField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="websites",
                        to="accounts.supplierprofile",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
