# Generated by Django 5.1.1 on 2024-10-16 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_faqquestionanswer"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="faqquestionanswer",
            options={"ordering": ["-weight", "question"]},
        ),
    ]
