# Generated by Django 5.1.1 on 2024-10-17 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0003_alter_faqquestionanswer_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("area", models.CharField(max_length=200)),
                ("weight", models.IntegerField(default=1)),
            ],
            options={
                "verbose_name": "Business Area",
                "verbose_name_plural": "Business Areas",
                "ordering": ["-weight", "area"],
            },
        ),
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=75)),
                ("weight", models.IntegerField(default=1)),
                (
                    "area",
                    models.ManyToManyField(
                        related_name="partners", to="pages.businessarea"
                    ),
                ),
            ],
            options={
                "verbose_name": "Partner",
                "verbose_name_plural": "Partners",
                "ordering": ["-weight", "name"],
            },
        ),
    ]
